name: Docker build and push wrapper
description: Allows attaching custom options to all docker builds
inputs:
  provenance:
    required: false
    default: false
    description: ""
  context:
    required: false
    default: "."
    description: ""
  file:
    required: true
    description: ""
  push:
    required: false
    default: true
    description: ""
  platforms:
    required: true
    description: ""
  tags:
    required: true
    description: ""
  target:
    required: true
    description: ""
  build-args:
    required: false
    description: ""
outputs:
  digest:
    description: ""
    value: ${{ steps.build.outputs.digest }}
runs:
  using: composite
  steps:
    - name: Build
      id: build
      uses: docker/build-push-action@48aba3b46d1b1fec4febb7c5d0c644b249a11355
      with:
        provenance: ${{ inputs.provenance }}
        context: ${{ inputs.context }}
        file: ${{ inputs.file }}
        push: ${{ inputs.push }}
        platforms: ${{ inputs.platforms }}
        tags: ${{ inputs.tags }}
        target: ${{ inputs.target }}
        build-args: ${{ inputs.build-args }}